<?php
        /**
        * Class SOAP_SERVER_UTIL
        *
        * @package Framework
        * @subpackage Utilities
        */
	 
	class SOAP_SERVER_UTIL extends SoapServer {
                
                /**
		 * Gets the plural of the given string 
		 *
		 * @param string $string string word to be pluralized
                 * @param integer $count the counter
		 */
		function get_plural_string($string,$count) {
			
		}
		
	}