<?php
        /**
        * Class BASE_CMODEL_SITE_CONTENT_IMPORT
        *
        * @package Framework
        * @subpackage Cmodels
        */

	class BASE_CMODEL_SITE_CONTENT_IMPORT extends MODEL_COMPLEX {
                
                /**
                 * Gets a zip file
                 * @param string $zip_file 
                 */
		public function get_zip($zip_file) {
			
			
		}					
	}